export const JOKE_FETCH_REQUEST = 'JOKE_FETCH_REQUEST';
export const JOKE_FETCH_REQUEST_SUCCESS = 'JOKE_FETCH_REQUEST_SUCCESS';
export const JOKE_FETCH_REQUEST_FAILURE = 'JOKE_FETCH_REQUEST_FAILURE';

export const JOKE_CLEAN_REQUEST = 'JOKE_CLEAN_REQUEST';